<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);WPF0001</NoWarn>
    <AssemblyName>SolutionBundler.Modern</AssemblyName>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Vazirmatn-Regular.ttf" />
  </ItemGroup>
</Project>
